# Generated by Django 6.0.2 on 2026-02-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_onlypdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltInPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
    ]
